language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"

env:
    global:
      - DJANGO_VERSION=3.0.7
      - DJANGO_SETTINGS_MODULE='blog.settings_dev'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -Wall manage.py test

branches:
  only:
    - master
    - develop
