# Generated by Django 3.0.2 on 2020-06-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_view',
            field=models.IntegerField(default=0, verbose_name='PV数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
